name: Security Scan (Trivy Nachtelijk)

on:
  schedule:
    - cron: '0 2 * * *'  # Draait automatisch elke nacht om 02:00 uur

jobs:
  trivy-security:
    runs-on: ubuntu-latest
    steps:
      - name: Trivy Vulnerability Scanner uitvoeren op GHCR image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/alexanderkiggen/dotnovi-2026-04:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'